# history settings
HISTFILE=~/.history_zsh
HISTSIZE=100000
SAVEHIST=100000
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
#setopt share_history
# set terminal title
precmd () {print -Pn "\e]0;%n@%m: %d\a"}

# other basic settings
setopt auto_pushd
setopt pushd_ignore_dups
setopt extendedglob
unsetopt beep
autoload -U url-quote-magic
zle -N self-insert url-quote-magic

# bind keys
bindkey -e
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# autocompletion
autoload -U compinit
compinit
zstyle :compinstall filename '/home/james/.zshrc'

# external files
source /usr/local/bin/virtualenvwrapper.sh
source ~/.aliases

# prompt
PROMPT='%F{blue}%~%f$(git_super_status)$ '
source /usr/local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh

# various exports
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
export EDITOR=vim
export GPGKEY=876302FC
export PATH=${PATH}:/usr/local/bin:~/.bin:~/code/go/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin
export WORKON_HOME=$HOME/.virtualenvs
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_REQUIRE_VIRTUALENV=true
export _JAVA_AWT_WM_NONREPARENTING=1
export GDK_NATIVE_WINDOWS=true
export GOPATH=$HOME/code/go/

eval `/usr/libexec/path_helper -s`


function frameworkpython3 {
    if [[ ! -z "$VIRTUAL_ENV" ]]; then
        PYTHONHOME=$VIRTUAL_ENV /usr/local/bin/python3 "$@"
    else
        /usr/local/bin/python3 "$@"
    fi
}
